import com.modrinth.minotaur.TaskModrinthUpload

buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        maven { url "https://plugins.gradle.org/m2/" }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}

plugins {
    id "com.matthewprenger.cursegradle" version "1.4.0"
    id "com.modrinth.minotaur" version "1.2.1"
}

apply plugin: 'net.minecraftforge.gradle'

group = "com.oitsjustjose.geolosys"
archivesBaseName = "Geolosys-${game_version}-${mod_version}"

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: "${mappings_version}"

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                geolosys {
                    source sourceSets.main
                }
            }
        }

        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                geolosys {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    // Journey Map API
    maven { url 'https://oss.sonatype.org/content/groups/public/' }
    // Immersive Engineering & Craft Tweaker 2
    maven { url 'https://maven.blamejared.com/' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${game_version}-${forge_version}"

    compileOnly fg.deobf("blusunrize:ImmersiveEngineering:${ie_version}")
    compileOnly "CraftTweaker2:CraftTweaker2-MC1120-Main:${crafttweaker_version}"
    compileOnly group: "info.journeymap", name: "journeymap-api", version: journeymap_version, changing: true
}

jar {
    manifest {
        attributes(["Specification-Title"     : "geolosys",
                    "Specification-Vendor"    : "oitsjustjose.com",
                    "Specification-Version"   : "1", // We are version 1 of ourselves
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : "${mod_version}",
                    "Implementation-Vendor"   : "oitsjustjose.com",
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.mod_version
    inputs.property "mcversion", project.game_version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.mod_version, 'mcversion': project.game_version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

build.dependsOn processResources

tasks.register('publish') {
    group "upload"
    description "Uploads to all repositories (Curse & Modrinth)"

    dependsOn 'curseforge'
    dependsOn 'modrinth'
}

tasks.register('modrinth', TaskModrinthUpload.class).configure {
    group "upload"
    description "Uploads to Modrinth project"

    dependsOn('assemble', 'reobfJar')

    token = project.hasProperty("MODRINTH_TOKEN") ? project.MODRINTH_TOKEN : ""
    projectId = 'gu7yAYhd'
    versionNumber = "${project.game_version}-${project.mod_version}"
    uploadFile = jar
    versionType = 'RELEASE'
    addGameVersion(project.game_version)
    changelog = file("./changelog.md").text
    addLoader('forge')
}

curseforge {
    apiKey = project.hasProperty("CURSEFORGE_API_KEY") ? project.CURSEFORGE_API_KEY : ""
    project {
        id = '271856'
        changelogType = 'markdown'
        changelog = file("./changelog.md")
        releaseType = 'release'
        addGameVersion "${game_version}"
        mainArtifact(jar) {
            displayName = "Geolosys ${game_version} ${mod_version}"
        }
    }
}

sourceSets { main { output.resourcesDir = output.classesDir } }
