buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        maven { url "https://plugins.gradle.org/m2/" }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
    dependencies {
        classpath "gradle.plugin.com.matthewprenger:CurseGradle:1.4.0"
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'com.matthewprenger.cursegradle'

group= "com.oitsjustjose.geolosys"
archivesBaseName = "Geolosys-${minecraft_version}"

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.

minecraft {
    mappings channel: 'snapshot', version: "${mappings_version}"

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }

        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

repositories {
    // Journey Map API
    maven { url 'https://oss.sonatype.org/content/groups/public/' }
    // Immersive Engineering & Craft Tweaker 2
    maven { url 'https://maven.blamejared.com/' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    // minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

    
	implementation fg.deobf("blusunrize:ImmersiveEngineering:${ie_version}")
    implementation fg.deobf("CraftTweaker2:CraftTweaker2-MC1120-Main:${crafttweaker_version}")
    compileOnly group: "info.journeymap", name: "journeymap-api", version: journeymap_version, changing: true
}

jar {
    manifest {
        attributes([
            "Specification-Title": "geolosys",
            "Specification-Vendor": "oitsjustjose.com",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "${mod_version}",
            "Implementation-Vendor" :"oitsjustjose.com",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

processResources {
    from(sourceSets.main) {
        include '**/*'
        expand '@MC_VERSION@': "${minecraft_version}"
    }

    from(sourceSets.main) {
        include '**/*'
        expand '@VERSION@': "${mod_version}"
    }
}

build.dependsOn processResources

curseforge {
  apiKey = project.hasProperty("CURSEFORGE_API_KEY") ? project.CURSEFORGE_API_KEY : ""
  project {
    id = '271856'
    changelogType = 'markdown'
    changelog = file("./changelog.md")
    releaseType = 'release'
    addGameVersion "${minecraft_version}"

    mainArtifact(jar) {
        displayName = "Geolosys ${minecraft_version} ${mod_version}"
    }
  }
}
