
plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
    id 'com.modrinth.minotaur' version '2.+'
    id 'com.matthewprenger.cursegradle' version '1.4.0+'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

group = mod_group_id
version = mod_version
base { archivesName = "${mod_name}-${minecraft_version}-${mod_version}" }

repositories { 
    mavenLocal() 
    maven { url = "https://maven.blamejared.com" }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version
    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" { // define mod <-> source bindings
            sourceSet(sourceSets.main)
        }
    }
}


configurations { runtimeClasspath.extendsFrom localRuntime }

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

publish {
    dependsOn 'curseforge'
    dependsOn 'modrinth'
}

curseforge {
    apiKey = project.hasProperty("CURSEFORGE_API_KEY") ? project.CURSEFORGE_API_KEY : ""
    project {
        id = '271856'
        changelogType = 'markdown'
        changelog = file("./changelog.md")
        releaseType = "${publication_release_type}"
        addGameVersion "NeoForge"
        addGameVersion "${minecraft_version}"
        mainArtifact(jar) {
            displayName = "${mod_name} ${minecraft_version} ${mod_version}"
        }
    }
}

modrinth {
    token = project.hasProperty("MODRINTH_TOKEN") ? project.MODRINTH_TOKEN : ""
    projectId = "aPBZx3jD"
    versionName = "${mod_name} ${minecraft_version} ${mod_version}"
    versionNumber = "${minecraft_version}-${mod_version}"
    versionType = "${publication_release_type}"
    uploadFile = jar
    gameVersions = ["${minecraft_version}"]
    loaders = ["neoforge"]
    changelog = file("./changelog.md").text
    dependencies { optional.project "patchouli" }
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
