# Neoforge specifics -- largely unchanging
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.125
neo_version_range=[21.1.125,)
loader_version_range=[1,)

# Mod Settings
mod_id=geolosys
mod_name=Geolosys
mod_license=GNU GPLv3
mod_version=7.0.11
mod_group_id=com.oitsjustjose.geolosys
mod_authors=oitsjustjose
mod_description=Systematic Terrafirma-like Ore Generation with Datapack and Mod Support!

# Release settings
publication_release_type=beta

# JVM Arg Specifications
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false
