# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
mod_version=7.0.14
mod_release_type=release
game_version=1.20.1
neo_version=47.1.106

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
