modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
issueTrackerURL="http://github.com/oitsjustjose/geolosys/issues"
license="GNU GPLv3"

[[mods]]
modId="geolosys"
version="${file.jarVersion}"
displayName="Geolosys"
displayURL="https://mods.oitsjustjose.com/Geolosys/"
credits="Contributors on GitHub"
authors="oitsjustjose"
description='''
A highly configurable terrafirmacraft-style ore generation mod which permits users to configure almost everything, add their own entries, and many compatibility integrations for other mods.

Support me on Patreon at https://patreon.com/oitsjustjose
'''
[[dependencies.geolosys]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.geolosys]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.geolosys]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.20.1,)"
    ordering="AFTER"
    side="BOTH"
